Mr PCN/PCNManager/PCNManager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrapper.urls')),
]

Mr PCN/PCNManager/scrapper/urls.py
from django.urls import path
from .views import ScrapView, FillEmailView, home, PCNListView, generate_pdf


app_name = 'scrapper'
urlpatterns = [
    path('scrap/', ScrapView.as_view(), name='scrap'),
    path('fill-email/', FillEmailView.as_view(), name='fillemail'),
    path('', home, name='home'),

    path('pcn-list/', PCNListView.as_view(), name='pcnlist'),
    path('generate-pdf/', generate_pdf, name='generatepdf'),
]

Mr PCN/PCNManager/scrapper/models.py
import email
from pyexpat import model
from django.db import models


class PCN(models.Model):
    pcn = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, blank=True, null=True)
    phone = models.TextField()
    location = models.CharField(max_length=255)
    control_number = models.CharField(max_length=30)
    subdivision = models.CharField(max_length=255)
    legal_description = models.TextField()

    def __str__(self):
        return self.pcn

class directory(models.Model):
    fname = models.CharField(max_length=500)
    lname = models.CharField(max_length=500)
    email = models.CharField(max_length=500)
    email_old = models.CharField(max_length=500)
    phone1 = models.CharField(max_length=500)    
    phone1_old = models.CharField(max_length=500)    
    phone2 = models.CharField(max_length=500)    
    phone2_old = models.CharField(max_length=500)    
    address = models.CharField(max_length=500)    
    city = models.CharField(max_length=500)    
    state = models.CharField(max_length=500)    
    zip = models.CharField(max_length=500)    
    community = models.CharField(max_length=500)    

    def __str__(self):
        return self.fname

Mr PCN/PCNManager/scrapper/forms.py
import re
from django import forms


class PCNForm(forms.Form):
    pcn = forms.CharField(max_length=14, required=False)
    pcn_file = forms.FileField(required=False)

    #use bootstrap form
    def __init__(self, *args, **kwargs):
        super(PCNForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-3 mr-sm-2'})


class EmailForm(forms.Form):
    email = forms.FileField(required=True)
    phone = forms.TextInput()
    # use bootstrap form
    def __init__(self, *args, **kwargs):
        super(EmailForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-3 mr-sm-2'})

Mr PCN/PCNManager/scrapper/views.py
from django.shortcuts import redirect, render

from django.views.generic import View
from django.views.generic.list import ListView
from urllib3 import HTTPResponse


import docx

import tempfile, shutil, os

from selenium.webdriver.common.by import By

from bs4 import BeautifulSoup
import time
import re
import requests

import pandas as pd

# load variables from __init__.py
from scrapper import browser

from .forms import PCNForm, EmailForm
from .models import PCN, directory

from django.conf import settings

from docx2pdf import convert 
from selenium.common.exceptions import InvalidSessionIdException
def home(request):
    return render(request, "base.html")

def scrap_data(pcn_list):
    pcn_numbers = pcn_list
    for pcn_number in pcn_numbers:
        print("Fetching data for " + pcn_number)
        browser.get(f'https://www.pbcgov.org/papa/Asps/GeneralAdvSrch/NewSearchResults.aspx?srchType=MASTER&proptype=RE&srchVal={pcn_number}&srchPCN=')
        print("Success getting the browser")
        loops = (int(browser.find_element(By.XPATH, '/html/body/form/div[3]/div/div/div[1]/table/tbody/tr[1]/td/table/tbody/tr/td[2]/i/b[3]').text) // 100) + 1 
        for pages in range(loops):
            try:
                print("Searching...")
                # Clicking on the dropdown menu.
                s100 = browser.find_element(By.NAME, 'ctl00$MainContent$ddlPgSizeTop').click()
                time.sleep(1)
                s100 = browser.find_element(By.NAME, 'ctl00$MainContent$ddlPgSizeTop').send_keys('100')
                print("Sorted by 100")
                time.sleep(2)

                soup = BeautifulSoup(browser.page_source, 'html.parser')
                time.sleep(2)

                sc_list = []

                for row in soup.find_all('tr', class_='gridrow2'):
                    t_datas = row.find_all('td')
                    print(t_datas)
                    try:
                        sc_list.append(t_datas[3].text)
                    except IndexError:
                        pass
                time.sleep(2)

                for row in soup.find_all('tr', class_='gridrowalternate2'):
                    t_datas = row.find_all('td')
                    try:
                        sc_list.append(t_datas[3].text)
                    except IndexError:
                        pass
                print(sc_list)

                def get_user_info(pc_num):
                    each_url = f'https://www.pbcgov.org/papa/Asps/PropertyDetail/PropertyDetail.aspx?parcel={pc_num}&srchtype=MASTER&srchVal=00-42-47-27-38'
                    tbs = []
                    sc_list = []
                    # try:
                    response = requests.get(each_url)
                    soup = BeautifulSoup(response.text, 'html.parser')
                    # find specific id
                    location_address = soup.find('span', id='MainContent_lblLocation').text
                    pcn = soup.find('span', id='MainContent_lblPCN').text
                    subdivision = soup.find('span', id='MainContent_lblSubdiv').text
                    legal_description = soup.find('span', id='MainContent_lblLegalDesc').text

                    
        
                    tbs = soup.find_all("table", {'width':'100%', 'cellspacing':'0', 'cellpadding':'1'})
                    print(tbs)
                    # except:
                    #     print("page unreachable")
                    for i in tbs:
                        for m in i.find_all('tr'):
                            for j in m.find_all('td', {'class': 'TDValueLeft', 'colspan': '2'}):
                                sc_list.append(j.text)

                    owners_name = []
                    for i in sc_list:
                        if i.startswith('\n'):
                            break
                        else:
                            owners_name.append(i)
                    for owner_name in owners_name:
                        # save the data to the PCN table
                        if '&' in owner_name:
                            owner_name = owner_name.replace('&', '')
                        print(owner_name)
                        try:
                            # if the data exists in the database, overwrite it
                            data = PCN.objects.filter(pcn=pcn, owner=owner_name, location=location_address, control_number=pc_num)
                            if data:
                                data.update(subdivision=subdivision, legal_description=legal_description)
                                print("already exists")
                            else:
                                print("saving new")
                                to_be = PCN.objects.create(
                                    pcn = pcn,
                                    owner = owner_name,
                                    location = location_address,
                                    subdivision = subdivision,
                                    legal_description = legal_description,
                                    control_number = pc_num
                                )
                                
                                # for i in owner_name.split():
                                e_p_data = directory.objects.filter(address__icontains=location_address.split()[0])[0]
                                print("found ",  e_p_data)
                                if e_p_data:
                                    to_be.email = e_p_data.email
                                    to_be.phone = f"{e_p_data.phone1}, {e_p_data.phone2}"
                
                                to_be.save()
                        except Exception as e:
                            print(e, "error")
                            pass
                        
                for pc_nums in sc_list:
                    time.sleep(2)
                    get_user_info(pc_nums)
                try:
                    browser.find_element(By.PARTIAL_LINK_TEXT,value="Next").click()
                except:
                    print("No more next page")
            except InvalidSessionIdException:
                self.driver.close() 
                print(">>>>> Selenuim just closed the winwdows..,")
            # except:
            #     print("Something went wrong")



class ScrapView(View):
    template_name = 'index.html'
    success_url = 'home'

    def get(self, request):
        form = PCNForm(request.POST or None, request.FILES or None)
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = PCNForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.cleaned_data
            pcn = form.get('pcn')
            pcn_file = form.get('pcn_file')
            pcn_list = []
            if pcn_file:
                pcn_csv = pd.read_csv(pcn_file)
                pcn_list = pcn_csv['pcn'].tolist()
            if pcn:
                pcn_list.append(pcn)        
            if pcn_list:
                scrap_data(pcn_list)
            else:
                print("No PCN")
        form = PCNForm(request.POST, request.FILES)
        return render(request, self.template_name, {'form': form})

class FillEmailView(View):
    template_name = 'fill_email.html'
    success_url = 'home'

    def get(self, request):
        form = EmailForm(request.POST or None, request.FILES or None)
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = EmailForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.cleaned_data
            email_file = request.FILES['email']
            email_csv = pd.read_csv(email_file)
            email_list = email_csv['email'].tolist()
            owner_list = email_csv['owner'].tolist()
            for owner, email in zip(owner_list, email_list):
                PCN.objects.filter(owner=owner).update(email=email)
        form = EmailForm(request.POST, request.FILES)
        return render(request, self.template_name, {'form': form})

class PCNListView(ListView):
    model = PCN
    paginate_by = 100
    template_name = 'pcn_list.html'
    context_object_name = 'pcn_list'


def generate_pdf(request):
# convert html file to pdf using weasyprint
    def create_temporary_copy(path):
        temp_dir = tempfile.gettempdir()
        temp_path = os.path.join(temp_dir, 'temp_file_name')
        shutil.copy2(path, temp_path)
        return temp_path

    data = PCN.objects.all()
    FLNAME = settings.FLNAME
    for i in data:
        mydoc = docx.Document(create_temporary_copy(FLNAME))
        h = mydoc.add_paragraph("WRITTEN CONSENT")
        # bold h
        h.runs[0].bold = True
        h.runs[0].font.name = 'Garamond'
        h.runs[0].font.size = docx.shared.Pt(12)
        h.alignment = docx.enum.text.WD_ALIGN_PARAGRAPH.CENTER
        x =  mydoc.add_paragraph("")
        f_name = ' '.join([i.owner.split()[1::-1][0]] + i.owner.split()[2:] +  [i.owner.split()[1::-1][1]])
        print(">>"*5,f_name)
        par = ["I, ", f_name," owner (and/or authorized representative of Florida Limited Liability Company or Florida Corporation owning a LOT in Boca Pointe Community Association) of LOT ", str(i.location), " with legal description of: ",' '.join(i.legal_description.split()), " in Boca Pointe Community Association Inc. hereby gives consent for revival of the Declaration of Covenants, Conditions, Restrictions and Easements of Boca Pointe Community Association pursuant to section 720.405(6), Florida Statutes.", "Owner (or authorization representative of Florida entity owning a property / LOT in Boca Pointe Community Association",
        "Signature: ______________________________",
        "Print Name: ",f_name,"      Date:  _____________________",
        "Title:Owner",
        "Florida Limited Liability Company name (if applicable):  ______________________________"

Mr PCN/PCNManager/scrapper/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>PCN Manager</title>
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">PCN Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'scrapper:scrap' %}">Scrap</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'scrapper:fillemail' %}">Fill Emails</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'scrapper:pcnlist' %}">View Data</a>
              </li>
        </div>
      </nav>
        <div class="container-sm">
            {% block scrapper %}
            {% endblock %}
        </div>

         <div class="container-sm">
            {% block email %}
            {% endblock %}
        </div>

        <div class="container-sm">
            {% block list %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

Mr PCN/PCNManager/scrapper/templates/fill_email.html
{% extends 'base.html' %}
{% load static %}

{% block email %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit" >Submit</button>
    </form>


{% endblock %}

Mr PCN/PCNManager/scrapper/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block scrapper %}


<div class="mb-3">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-success" type="submit" >Submit</button>
    </form>
</div>
{% endblock %}

Mr PCN/PCNManager/scrapper/templates/pcn_list.html
{% extends 'base.html' %}
{% load static %}

{% block list %}
<table class="table">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Owner</th>
          <th scope="col">PCN</th>
          <th scope="col">Email</th>
          <th scope="col">Address</th>
        </tr>
      </thead>
      <tbody>
        {% for pcn in object_list %}
        <tr>
          <th scope="row">{{pcn.id}}</th>
          <td>{{ pcn.owner }}</td>
          <td>{{ pcn.pcn}}</td>
          <td>{{ pcn.email}}</td>
          <td>{{ pcn.location}}</td>
        </tr>
        {% endfor %}
</table>
    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{i}} <span class="sr-only"></span></a></li>
        {% else %}
          <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        
      {% else %}
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}